### ISSUE TITLE
Support general color maps

### ISSUE THREAD

**Issue by MarcSkovMadsen** [developmentseed/lonboard#263]
It seems your `apply_continuous_cmap` is very tied to palettable.

I experienced this a friction as I'm used to using Colorcet. So I ended up creating some functionality to convert from colorcet to palettable in #262.

I'm not very well versed in colormaps but I would think that tying it to one provider is friction.

**Comment by kylebarron** [comment]
I hadn't previously used colormaps in python much, and so I figured the easiest approach was to nudge people towards a library with lots of colormaps. 

To be clear, `apply_continuous_cmap` is only a _helper_ for creating a numpy array that's of shape `(n, 3)` or `(n, 4)` and data type `uint8` for passing into anything that accepts a color. Part of the primary goal in lonboard is to say "use the full range of python to do _whatever you want_ that outputs a column of colors to render". So for example, I'm not familiar with colorcet but it looks like you can get [matplotlib-compatible colormaps](https://colorcet.holoviz.org/user_guide/index.html#using-colorcet-via-matplotlib-cm-get-cmap) easily. So you can do

```py
from matplotlib.cm import get_cmap

data = np.array(...)
colormap = get_cmap("cet_fire")
map_.get_fill_color = colormap(data, bytes=True)
```
(`bytes=True` makes it uint8 output 0-255 instead of float 0-1).

That said, it's probably good to update `apply_continuous_cmap` to support at least either any `palettable` colormap or any matplotlib colormap object (though for the matplotlib colormap it would literally just be an alias to call `colormap(data, bytes=True)`.
