### ISSUE TITLE
support classification schemes

### ISSUE THREAD

**Issue by knaaptime** [developmentseed/lonboard#593]
Hi folks, thanks for all your work on this; lonboard has been lovely! I'm curious if there is interest in supporting commonly-used map classification schemes (a-la the `scheme` argument in geopandas's plot function) under the hood (particularly in the `viz` API)? We just added [a small function in mapclassify](https://github.com/pysal/mapclassify/blob/main/notebooks/08_manual_coloring.ipynb) that makes it much easier to grab a color set from matplotlib than the one geopandas is using manually at the moment

From a users' perspective, it would be sweet if `viz` had parity with geopandas's `explore`, though of course, it's also easy to just pass the colors in manually, so no worries if it's not in scope :)

**Comment by kylebarron** [comment]
👋 I've wanted to explore better integration with mapclassify for a while (https://github.com/developmentseed/lonboard/issues/136). In general I'm working to minimize Lonboard's (required) dependencies (e.g. https://github.com/developmentseed/lonboard/pull/472 and https://github.com/developmentseed/lonboard/pull/582).

It would definitely be good to have an example of how to use with mapclassify. It might be in scope to make mapclassify an optional dependency so that `viz` can be closer to parity with `explore`, and to raise an `ImportError` if `mapclassify` isn't installed and the user wants to use a classification scheme. I don't think I want to add mapclassify as a hard dependency though.

**Comment by knaaptime** [comment]
sweet (sorry, missed that issue, can close this in its favor); makes perfect sense to me and would be exactly how geopandas treats it (def don't want a hard dependency).

(FWIW, longraph is fun with [other parts of pysal too](https://knaaptime.com/longraph/) :)

**Comment by kylebarron** [comment]
Longraph looks really cool!

I'm not very familiar with mapclassify or classification schemes in general, so if you ever get the itch, an example notebook here using mapclassify would be welcomed 🙂

**Comment by knaaptime** [comment]
yep, happy to  (thanks! props to you, really. Lonboard does the heavy lifting; good docs count)


there's a short example with lonboard [in cell 8](https://github.com/pysal/mapclassify/blob/main/notebooks/08_manual_coloring.ipynb) but will throw a more detailed on together quickly

**Comment by knaaptime** [comment]
though it occurs to me there's also the long-winded version on classification scheme *with* mapclassify [here](https://knaaptime.com/urban_analysis/01_geoprocessing/01_geovisualization.html#map-classifiers) and [here](https://geographicdata.science/book/notebooks/05_choropleth.html), fwiw

**Comment by kylebarron** [comment]
I figure a minimal example notebook is fine that then links to those in-depth resources. It's good to have the visibility that the libraries work together, and then the user can dig into mapclassify to figure out exactly what they want.
