### ISSUE TITLE
Add additional filter types to DataFilterExtension

### ISSUE THREAD

**Issue by tylere** [developmentseed/lonboard#615]
**Is your feature request related to a problem? Please describe.**

I would like to use the value from a single valued widget (examples: [IntSlider](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#intslider), FloatSlider, Dropdown, RadioButtons, Select, etc.) to filter a layer.

**Describe the solution you'd like**

In addition to the currently existing [filter_range](https://developmentseed.org/lonboard/latest/api/layer-extensions/data-filter-extension/#lonboard.layer_extension.DataFilterExtension--filter_enabled) option provided by the DataFilterExtension, I would also like these additional options:

- `filter_equals` (for integers)
- `filter_gt` (greater than, for floats or integers)
- `filter_gte` (greater than or equals, for floats or integers)
- `filter_lt` (less than, for floats or integers)
- `filter_lte` (less than or equals, for floats or integers)

These filters could be used with single-valued (non-range) widgets.

**Describe alternatives you've considered**

It might be possible to create a custom non-GUI widget that converts the output of a single-valued widget into a range. Something like:

```mermaid
flowchart LR
    A[IntSlider widget] -->|value| B(IntToIntRange widget)
    B --> |range| C[Lonboard widget]
```

**Additional context**

I have been trying to use [filter_range](https://developmentseed.org/lonboard/latest/api/layer-extensions/data-filter-extension/#lonboard.layer_extension.DataFilterExtension--filter_range), but that is a bad user experience that requires a user to manipulate both ends of the range selector.

![Screenshot 2024-08-27 at 11 56 29 AM](https://github.com/user-attachments/assets/958ec208-2edb-415c-aacd-88d69b9fa246)

**Comment by kylebarron** [comment]
👋 

The only API that deck.gl provides to us is [`filterRange`](https://deck.gl/docs/api-reference/extensions/data-filter-extension#filterrange). (Plus [`filterCategories`](https://deck.gl/docs/api-reference/extensions/data-filter-extension#filtercategories), which is new in deck.gl v9 and we recently merged to Lonboard, see https://github.com/developmentseed/lonboard/pull/609)

Other APIs would really have to be implemented in deck.gl first, unless we did some magic on our own side to pass into `filterRange`. 

> filter_equals (for integers)

As of today, the DataFilterExtension exclusively uses float32 values. So even if you pass in integer data to Lonboard, deck.gl's filtering is done on float32 values. See ["filter precision"](https://deck.gl/docs/api-reference/extensions/data-filter-extension#filter-precision).

This will likely change in the next year or two, since new GPU technology (WebGPU) is coming to browsers, but today, under the hood everything uses floats. You could still in theory get integer equality up to the maximum integers that a float can represent, I suppose?

**Comment by kylebarron** [comment]
Realistically this isn't something we have the power to change. As deck.gl provides new APIs we'll expose them through Lonboard.
