### ISSUE TITLE
Pass color to `.viz` for a given table

### ISSUE THREAD

**Issue by ncclementi** [developmentseed/lonboard#632]
Not sure if the title is the best description but this is what I'd like to do. 

At the moment I have two different tables (minor_lines and power_lines) that have more than one type of geometry (lines and polygons) in their geometry column. I'd like to plot both tables with different colors that I can choose. At the moment these colors are different but assigned automatically.

```
lonboard.viz([minor_lines, power_lines])
```

![Screenshot 2024-09-13 at 2 02 04 PM](https://github.com/user-attachments/assets/55dd4354-7e7e-4ecf-a001-bf8230753f3f)

I want everything related to `minor_lines` to be one color, and for `power_lines` a different one.

**Comment by ATL2001** [comment]
That is the intention of .viz(), to just get _something_ to show up on the map.  If you want to control the color of the data on the map you should create individual layers from the data and add them to a map.  [The PathLayer documentation has a good example of the steps.](https://developmentseed.org/lonboard/latest/api/layers/path-layer/)

**Comment by ncclementi** [comment]
I'm very familiar with the individual layers, my problem is that the geometry column has a mix of Lines and polygons , and in the other case Lines and points so I can't separate them to be able to create the different layers.

**Comment by kylebarron** [comment]
👋 And thanks for chiming in @ATL2001.

I'd say the primary issue here is not a defect in viz, but rather the fact that it's hard to separate a table with mixed geometries into geometry-specific sub-tables. I don't really want to make `viz` more customizable here, because it should be just for seeing something on the map.

If you're able to extract into a table for each geometry type, then you can specify the color on each layer yourself.

In the long term, we should have the equivalent of the deck.gl `GeoJsonLayer` to let you plot a single table with customizations. We might be able to make this a Python-only layer for now, which under the hood renders multiple other Python layers, but in the longer term this would need to be a new layer on the JS side. We could call that the `GeoArrowLayer`, but the worry is that that leaks implementation details and GeoArrow doesn't have the name recognition yet of GeoJSONLayer

**Comment by ncclementi** [comment]
Sounds good, closing this then!
